services:
  user-service:
    build:
      context: ./user-service
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      psql:
        condition: service_healthy

  task-service:
    build:
      context: ./task-service
    env_file:
      - .env
    ports:
      - "8005:8005"
    depends_on:
      psql:
        condition: service_healthy

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  psql_volume:

