services:
  task:
    build:
      context: ./task
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      rabbit1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=:5000"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./auth
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      task:
        condition: service_healthy

  notification:
    build:
      context: ./notification
    env_file:
      - .env
    depends_on:
      rabbit1:
        condition: service_healthy

  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit1:
    env_file:
      - .env
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_volume:
