services:
  auth:
    build:
      context: ./auth
    env_file:
      - .env
    ports:
      - "4040:4040"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=:4040"]
      interval: 5s
      timeout: 5s
      retries: 5
  task:
    build:
      context: ./task
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      rabbit1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=:8080"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      auth:
        condition: service_healthy
      task:
        condition: service_healthy

  notification:
    build:
      context: ./notification
    env_file:
      - .env
    depends_on:
      rabbit1:
        condition: service_healthy

  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit1:
    env_file:
      - .env
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prometheus:
    image: prom/prometheus:v2.45.2
    user: root
    volumes:
      - "./monitoring/prometheus:/monitoring/prometheus"
      - "./var/prometheus/prometheus_data:/prometheus"
    command:
      - "--config.file=/monitoring/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9000:9090"

volumes:
  db_volume:
  prometheus_volume:
