// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sejamuchhal/taskhub/notification/worker (interfaces: EmailSenderInterface)

// Package mock_email_sender is a generated GoMock package.
package mock_email_sender

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mailersend "github.com/mailersend/mailersend-go"
)

// MockEmailSenderInterface is a mock of EmailSenderInterface interface.
type MockEmailSenderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderInterfaceMockRecorder
}

// MockEmailSenderInterfaceMockRecorder is the mock recorder for MockEmailSenderInterface.
type MockEmailSenderInterfaceMockRecorder struct {
	mock *MockEmailSenderInterface
}

// NewMockEmailSenderInterface creates a new mock instance.
func NewMockEmailSenderInterface(ctrl *gomock.Controller) *MockEmailSenderInterface {
	mock := &MockEmailSenderInterface{ctrl: ctrl}
	mock.recorder = &MockEmailSenderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSenderInterface) EXPECT() *MockEmailSenderInterfaceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailSenderInterface) SendEmail(arg0, arg1, arg2 string) (*mailersend.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*mailersend.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailSenderInterfaceMockRecorder) SendEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailSenderInterface)(nil).SendEmail), arg0, arg1, arg2)
}
